### ISSUE TITLE
DO1_2016_01_13 - Titulos de Tabelas - Pags 44 à 47

### ISSUE THREAD

**Issue by lcarli** [DXBrazil/PdfTextReader#34]
Tentar eliminar todo texto centralizado que vem antes das tabelas

EXCLUIR OS CASOS COM A PALAVRA ANEXO. Elas devem permanecer

**Comment by lcarli** [comment]
![image](https://user-images.githubusercontent.com/4472823/35382105-6bd3f1f2-01a5-11e8-9100-328e21223db8.png)

**Comment by fcatae** [comment]
Podemos dizer que tabelas sempre pertence a anexos?

**Comment by lcarli** [comment]
Sim! Dessa forma criaremos um padrão para nosso XML

**Comment by fcatae** [comment]
Pelo que entendi da sugestão:
- Remover texto centralizado que antecede uma tabela
- Exceção: texto centralizado que contenha a palavra anexo

Nessas condições, não pretendo alterar a lógica porque o texto centralizado (no exemplo) pertence a tabela. É como o título da tabela e não do Blockset.
