### ISSUE TITLE
DO1_2016_01_08: Linha do corpo como centralizado

### ISSUE THREAD

**Issue by lcarli** [DXBrazil/PdfTextReader#42]
Página 45!

![image](https://user-images.githubusercontent.com/4472823/35383087-6523be66-01a8-11e8-9be7-f1ed8b7e160a.png)

**Comment by lcarli** [comment]
![image](https://user-images.githubusercontent.com/4472823/35383889-cac30aea-01aa-11e8-8f54-74ba6c42cfed.png)

**Comment by fcatae** [comment]
Não consigo encontrar a página 45 - mas revisei os documentos dos dias 8 e 13 e não encontrei erros.
