### ISSUE TITLE
DO1_2016_01_15 - Tratamento de Decisões- Assinatura ERRADA (TextStructure)!

### ISSUE THREAD

**Issue by lcarli** [DXBrazil/PdfTextReader#51]
![image](https://user-images.githubusercontent.com/4472823/35386836-93ef3e3a-01b4-11e8-829b-0695d5ae27a3.png)

**Comment by fcatae** [comment]
Pagina 45 resolvida no CreateStructuresV2

**Comment by fcatae** [comment]
Prototipando ainda... mas provavelmente temos que mudar a estrutura.

**Comment by fcatae** [comment]
![image](https://user-images.githubusercontent.com/7252609/35417074-ece0f41c-0212-11e8-94d5-df1e54e24034.png)

**Comment by lcarli** [comment]
O problema aqui será como vamos usar os parágrafos... Na verdade, esse parágrafo ajuda o título, entende? É bem complicado esse caso.

**Comment by fcatae** [comment]
Esse é o problema da semântica... lembra o issue #43, que requer um tratamento diferenciado para Ementa.
