### ISSUE TITLE
DO1_2016_01_08: Alinhamento esquerda incorreto

### ISSUE THREAD

**Issue by fcatae** [DXBrazil/PdfTextReader#54]
![image](https://user-images.githubusercontent.com/7252609/35404274-89b242fc-01e9-11e8-81e6-dc62fa51c3a2.png)

**Comment by fcatae** [comment]
Causa: Não pertencem a mesma estrutura de parágrafo.

```

-----------------------------------
Aligment: RIGHT
A PRESIDENTA DA REPÚBLICA, no uso da atribuição (Times-Bold, 7.97, Regular)
 (2.00927)


-----------------------------------
Aligment: JUSTIFY
que lhe confere o art. 84, caput, inciso VI, alínea "a", da Cons-
tituição, (Times-Roman, 7.97, Regular)
 ()
```

**Comment by lcarli** [comment]
Esse caso também precisa ser discutido. No caso em que aparece a frase, eu pós-processo. Só que existem outros casos com outras frases (ex. O Ministro do STF; O Presidente do conselho; etc). 
Não sei se o correto seria só pós processar criando um dicionário de possibilidades...

**Comment by fcatae** [comment]
Causa: primeira linha era considerada com fonte BOLD, enquanto que a segunda, REGULAR. 
Corrigido: Quando detectado duas fontes no mesmo texto, então considera o REGULAR.
![image](https://user-images.githubusercontent.com/7252609/37991323-3e535c94-31df-11e8-98f7-c866be023cc4.png)
