### ISSUE TITLE
Texto abaixo do Titulo Portaria foi considerado Corpo

### ISSUE THREAD

**Issue by dansemedo** [DXBrazil/PdfTextReader#56]
![bugparser2](https://user-images.githubusercontent.com/34478209/35405985-dbeae33a-01ee-11e8-8811-a77412be50de.png)

**Comment by lcarli** [comment]
Está correto considerar corpo. Mas deveria ter vindo o corpo todo...

**Comment by fcatae** [comment]
Comportamento correto. Inclusive o corpo.
![image](https://user-images.githubusercontent.com/7252609/37991671-2e13c16a-31e0-11e8-99c2-ee4bb2ea67c7.png)
